name: Giffy
include:
  - .swiftlint.yml
  - path: .swiftlint.yml
    relativePaths: false
options:
  bundleIdPrefix: "com.uwaisalqadri"
  deploymentTarget:
    iOS: 17.0
  postGenCommand: xcodebuild -resolvePackageDependencies
  indentWidth: 2
  tabWidth: 2
  groupOrdering:
    - order:
      - Giffy
      - GiffyWidget
      - Packages
packages:
  SDWebImageSwiftUI:
    github: SDWebImage/SDWebImageSwiftUI
    version: 3.0.2
  Swinject:
    github: Swinject/Swinject
    version: 2.8.0
  Lottie:
    github: airbnb/lottie-spm
    version: 4.3.0
  netfox:
    github: kasketis/netfox
    version: 1.21.0
  Common:
    path: Modules/Common/Common
  CommonUI:
    path: Modules/CommonUI/CommonUI
targets:
  Giffy:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    scheme:
      testTargets:
        - GiffyTests
      gatherCoverageData: true
    dependencies:
      - target: GiffyWidget
      - package: Common
      - package: CommonUI
      - package: SDWebImageSwiftUI
      - package: Swinject
      - package: Lottie
      - package: netfox
    sources:
      - path: Giffy
        excludes:
          - "**/*.md" # excludes all files with the .md extension
    settings:
      base:
        API_KEY: EEx8BY3HX9JrYdFZ4Hdcx4Trbj35k5Ic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 1.0.0
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        ENABLE_BITCODE: false
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/Giffy"
    postCompileScripts:
      - script: |
          if test -d "/opt/homebrew/bin/"; then
            PATH="/opt/homebrew/bin/:${PATH}"
          fi
          
          export PATH
          
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  
  GiffyWidget:
    type: app-extension
    subtype: widgetkit-extension
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.uwaisalqadri.Giffy.GiffyWidget
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: GiffyWidget/Info.plist
    sources:
      - path: GiffyWidget
    dependencies:
      - package: CommonUI
      - package: Common
      - package: SDWebImageSwiftUI
      - package: Swinject
      - package: Lottie
      - package: netfox
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
  GiffyTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - target: Giffy
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: GiffyTests/Info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Giffy.app/Giffy
    scheme:
      testTargets:
        - GiffyTests
    sources:
      - path: GiffyTests
